/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as CrmNoteIdRouteImport } from './routes/crm/$noteId'
import { Route as MarketIntelligenceIndexRouteImport } from './routes/market-intelligence/index'
import { Route as MarketIntelligenceEventIdRouteImport } from './routes/market-intelligence/$eventId'
import { Route as ProductKnowledgeIndexRouteImport } from './routes/product-knowledge/index'
import { Route as ProductKnowledgeTestIdRouteImport } from './routes/product-knowledge/$testId'
import { Route as ProvidersNpiRouteImport } from './routes/providers/$npi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmNoteIdRoute = CrmNoteIdRouteImport.update({
  id: '/crm/$noteId',
  path: '/crm/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIntelligenceIndexRoute = MarketIntelligenceIndexRouteImport.update({
  id: '/market-intelligence/',
  path: '/market-intelligence/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIntelligenceEventIdRoute =
  MarketIntelligenceEventIdRouteImport.update({
    id: '/market-intelligence/$eventId',
    path: '/market-intelligence/$eventId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductKnowledgeIndexRoute = ProductKnowledgeIndexRouteImport.update({
  id: '/product-knowledge/',
  path: '/product-knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductKnowledgeTestIdRoute = ProductKnowledgeTestIdRouteImport.update({
  id: '/product-knowledge/$testId',
  path: '/product-knowledge/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersNpiRoute = ProvidersNpiRouteImport.update({
  id: '/providers/$npi',
  path: '/providers/$npi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm/$noteId': typeof CrmNoteIdRoute
  '/market-intelligence/$eventId': typeof MarketIntelligenceEventIdRoute
  '/product-knowledge/$testId': typeof ProductKnowledgeTestIdRoute
  '/providers/$npi': typeof ProvidersNpiRoute
  '/crm/': typeof CrmIndexRoute
  '/market-intelligence/': typeof MarketIntelligenceIndexRoute
  '/product-knowledge/': typeof ProductKnowledgeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm/$noteId': typeof CrmNoteIdRoute
  '/market-intelligence/$eventId': typeof MarketIntelligenceEventIdRoute
  '/product-knowledge/$testId': typeof ProductKnowledgeTestIdRoute
  '/providers/$npi': typeof ProvidersNpiRoute
  '/crm': typeof CrmIndexRoute
  '/market-intelligence': typeof MarketIntelligenceIndexRoute
  '/product-knowledge': typeof ProductKnowledgeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm/$noteId': typeof CrmNoteIdRoute
  '/market-intelligence/$eventId': typeof MarketIntelligenceEventIdRoute
  '/product-knowledge/$testId': typeof ProductKnowledgeTestIdRoute
  '/providers/$npi': typeof ProvidersNpiRoute
  '/crm/': typeof CrmIndexRoute
  '/market-intelligence/': typeof MarketIntelligenceIndexRoute
  '/product-knowledge/': typeof ProductKnowledgeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm/$noteId'
    | '/market-intelligence/$eventId'
    | '/product-knowledge/$testId'
    | '/providers/$npi'
    | '/crm/'
    | '/market-intelligence/'
    | '/product-knowledge/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crm/$noteId'
    | '/market-intelligence/$eventId'
    | '/product-knowledge/$testId'
    | '/providers/$npi'
    | '/crm'
    | '/market-intelligence'
    | '/product-knowledge'
  id:
    | '__root__'
    | '/'
    | '/crm/$noteId'
    | '/market-intelligence/$eventId'
    | '/product-knowledge/$testId'
    | '/providers/$npi'
    | '/crm/'
    | '/market-intelligence/'
    | '/product-knowledge/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmNoteIdRoute: typeof CrmNoteIdRoute
  MarketIntelligenceEventIdRoute: typeof MarketIntelligenceEventIdRoute
  ProductKnowledgeTestIdRoute: typeof ProductKnowledgeTestIdRoute
  ProvidersNpiRoute: typeof ProvidersNpiRoute
  CrmIndexRoute: typeof CrmIndexRoute
  MarketIntelligenceIndexRoute: typeof MarketIntelligenceIndexRoute
  ProductKnowledgeIndexRoute: typeof ProductKnowledgeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/$noteId': {
      id: '/crm/$noteId'
      path: '/crm/$noteId'
      fullPath: '/crm/$noteId'
      preLoaderRoute: typeof CrmNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-intelligence/': {
      id: '/market-intelligence/'
      path: '/market-intelligence'
      fullPath: '/market-intelligence/'
      preLoaderRoute: typeof MarketIntelligenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-intelligence/$eventId': {
      id: '/market-intelligence/$eventId'
      path: '/market-intelligence/$eventId'
      fullPath: '/market-intelligence/$eventId'
      preLoaderRoute: typeof MarketIntelligenceEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-knowledge/': {
      id: '/product-knowledge/'
      path: '/product-knowledge'
      fullPath: '/product-knowledge/'
      preLoaderRoute: typeof ProductKnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-knowledge/$testId': {
      id: '/product-knowledge/$testId'
      path: '/product-knowledge/$testId'
      fullPath: '/product-knowledge/$testId'
      preLoaderRoute: typeof ProductKnowledgeTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$npi': {
      id: '/providers/$npi'
      path: '/providers/$npi'
      fullPath: '/providers/$npi'
      preLoaderRoute: typeof ProvidersNpiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmNoteIdRoute: CrmNoteIdRoute,
  MarketIntelligenceEventIdRoute: MarketIntelligenceEventIdRoute,
  ProductKnowledgeTestIdRoute: ProductKnowledgeTestIdRoute,
  ProvidersNpiRoute: ProvidersNpiRoute,
  CrmIndexRoute: CrmIndexRoute,
  MarketIntelligenceIndexRoute: MarketIntelligenceIndexRoute,
  ProductKnowledgeIndexRoute: ProductKnowledgeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
